name: Deploy to Server

on:
  push:
    branches:
      - feature/chatbot_victor
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: chatbot_pds_api
      SERVER_USER: dmillar
      SERVER_IP: 200.13.4.225
      INTERNAL_PORT: 5000
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME ./chatbot-pds-api/chatbot_project

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Save and send Docker image
        run: |
          docker save $IMAGE_NAME | gzip > $IMAGE_NAME.tar.gz
          scp $IMAGE_NAME.tar.gz $SERVER_USER@$SERVER_IP:/tmp

      - name: Deploy on server
        run: |
          ssh $SERVER_USER@$SERVER_IP <<EOF
            set -e
            gunzip -c /tmp/$IMAGE_NAME.tar.gz | docker load
            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true
            docker run -d --name $IMAGE_NAME -p $INTERNAL_PORT:$INTERNAL_PORT -e FLASK_ENV=production -e FLASK_DEBUG=0 -e FLASK_RUN_PORT=$INTERNAL_PORT -e WEATHER_API_KEY=$WEATHER_API_KEY $IMAGE_NAME
          EOF
